// <auto-generated />
using System;
using JobsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobsApi.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    [Migration("20220628151848_InitialMigrationWithData")]
    partial class InitialMigrationWithData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JobsApi.Models.JobInfo", b =>
                {
                    b.Property<DateTime>("JobDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ActiveJobs")
                        .HasColumnType("int");

                    b.Property<int>("JobViews")
                        .HasColumnType("int");

                    b.Property<int>("PredictedJobViews")
                        .HasColumnType("int");

                    b.HasKey("JobDate");

                    b.ToTable("JobInfo", (string)null);

                    b.HasData(
                        new
                        {
                            JobDate = new DateTime(2022, 6, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 5,
                            JobViews = 3,
                            PredictedJobViews = 2
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 10,
                            JobViews = 6,
                            PredictedJobViews = 4
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 15,
                            JobViews = 9,
                            PredictedJobViews = 6
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 20,
                            JobViews = 12,
                            PredictedJobViews = 8
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 25,
                            JobViews = 15,
                            PredictedJobViews = 10
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 30,
                            JobViews = 18,
                            PredictedJobViews = 12
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 35,
                            JobViews = 21,
                            PredictedJobViews = 14
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 40,
                            JobViews = 24,
                            PredictedJobViews = 16
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 45,
                            JobViews = 27,
                            PredictedJobViews = 18
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 50,
                            JobViews = 30,
                            PredictedJobViews = 20
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 55,
                            JobViews = 33,
                            PredictedJobViews = 22
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 60,
                            JobViews = 36,
                            PredictedJobViews = 24
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 65,
                            JobViews = 39,
                            PredictedJobViews = 26
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 70,
                            JobViews = 42,
                            PredictedJobViews = 28
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 75,
                            JobViews = 45,
                            PredictedJobViews = 30
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 80,
                            JobViews = 48,
                            PredictedJobViews = 32
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 85,
                            JobViews = 51,
                            PredictedJobViews = 34
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 90,
                            JobViews = 54,
                            PredictedJobViews = 36
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 95,
                            JobViews = 57,
                            PredictedJobViews = 38
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 100,
                            JobViews = 60,
                            PredictedJobViews = 40
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 105,
                            JobViews = 63,
                            PredictedJobViews = 42
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 110,
                            JobViews = 66,
                            PredictedJobViews = 44
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 115,
                            JobViews = 69,
                            PredictedJobViews = 46
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 120,
                            JobViews = 72,
                            PredictedJobViews = 48
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 125,
                            JobViews = 75,
                            PredictedJobViews = 50
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 130,
                            JobViews = 78,
                            PredictedJobViews = 52
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 135,
                            JobViews = 81,
                            PredictedJobViews = 54
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 5, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 140,
                            JobViews = 84,
                            PredictedJobViews = 56
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 5, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 145,
                            JobViews = 87,
                            PredictedJobViews = 58
                        },
                        new
                        {
                            JobDate = new DateTime(2022, 5, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ActiveJobs = 150,
                            JobViews = 90,
                            PredictedJobViews = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
